# Generated by Django 5.0.7 on 2024-07-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='mobile_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
