# Generated by Django 5.0.7 on 2024-07-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='slider_image',
            field=models.ImageField(upload_to='static/uploads/'),
        ),
    ]
