# Generated by Django 5.0.7 on 2024-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_sliderimage_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_heading', models.CharField(max_length=100)),
                ('slider_content', models.TextField()),
                ('slider_button_text', models.CharField(max_length=90)),
                ('slider_button_link', models.TextField()),
            ],
        ),
    ]
