# Generated by Django 5.0.7 on 2024-07-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_homeaboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeAboutUs',
        ),
    ]
