# Generated by Django 5.0.7 on 2024-07-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_image',
            field=models.ImageField(null=True, upload_to='static/uploads/'),
        ),
    ]
