# Generated by Django 5.0.7 on 2024-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='img_testimnials',
            field=models.ImageField(null=True, upload_to='static/uploads/'),
        ),
    ]
