# Generated by Django 5.0.7 on 2024-07-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_testimonials_img_testimnials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='static/uploads/')),
                ('blog_city', models.CharField(max_length=20)),
                ('blog_info', models.CharField(max_length=100)),
                ('blog_date', models.DateField()),
            ],
        ),
    ]
