# Generated by Django 5.0.7 on 2024-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='services_details',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
