# Generated by Django 5.0.7 on 2024-07-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(upload_to='static/uploads/')),
                ('about_title', models.CharField(max_length=100)),
            ],
        ),
    ]
